-- ==========================================
-- Supabase Schema Initialization Script
-- ==========================================

-- 1. Create `users` table
CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  role text,
  status text DEFAULT 'active',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create `swaps` table
CREATE TABLE public.swaps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  offering text NOT NULL,
  status text DEFAULT 'NEW',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create `plots` table
CREATE TABLE public.plots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  available_sqft integer NOT NULL DEFAULT 0,
  host_id bigint REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- Insert Initial Mock Data
-- ==========================================
INSERT INTO public.users (id, name, role, status) VALUES
  (1, 'Alice M.', 'Moderator', 'active'),
  (2, 'Bob K.', 'Gardener', 'inactive');

INSERT INTO public.swaps (id, title, offering, status) VALUES
  (1, 'Japanese Red Maple', 'Heirloom Kale', 'PENDING'),
  (2, 'Carbon Steel Spade', 'Borrowing for 3 days', 'ACTIVE');

INSERT INTO public.plots (id, title, available_sqft, host_id) VALUES
  (1, 'Rooftop Plot #204', 12, 1),
  (2, 'Sunny Balcony', 20, 2);

-- Reset sequence counters so new records start from ID 100
ALTER SEQUENCE public.users_id_seq RESTART WITH 100;
ALTER SEQUENCE public.swaps_id_seq RESTART WITH 100;
ALTER SEQUENCE public.plots_id_seq RESTART WITH 100;

-- ==========================================
-- Row Level Security (RLS) Configurations
-- ==========================================
-- For immediately testing this in your app, we will disable RLS.
-- WARNING: In a production app with authentication, you MUST enable RLS
-- and write security policies (e.g. `create policy...`)!

ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.swaps DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.plots DISABLE ROW LEVEL SECURITY;
